### ISSUE TITLE
Impossible to send approve without ETH for gas

### ISSUE THREAD

**Issue by 99hops** [lessmore92/PHPEthereumERC20#10]
@lessmore92 Hello mate, you state that by
```
//by this method we allow $myapp_address to send upto 99999 token behalf of $owner_address
$approve_tx    = $token->approve($owner_address, $myapp_address, 99999);
$approve_tx_id = $approve_tx->sign($owner_private)
                            ->send()
```

$owner_address allows $myapp_address to send some USDT amount to any address without $owner_address having anything but USDT in his wallet. 

Well how is this possible to work while for approve() to work you have to send a transaction which needs gas (ETH)?

I tried with account only having token inside and got 
```
message: "insufficient funds for transfer"
code: -32000
```

Here is a [TX](https://etherscan.io/tx/0x30a3854b87260c24b7cd04dada569a407f294768446d531400fe149d21533586) on etherscan showing the exact approve() method called that costs $31 :smiley:

**Comment by lessmore92** [comment]
Hi,
`approve` is a transaction that needs to be paid a fee.
Yes, for the `approve` method you need to pay the fee from the owner's address. So for the first transaction that does the `approve`,  address needs to have some ETH for gas.

**Comment by 99hops** [comment]
I agree, just wanted to point this out, thanks :beers: !

**Comment by lessmore92** [comment]
Thank you, I will update the doc.
