### ISSUE TITLE
CURL ERROR

### ISSUE THREAD

**Issue by lhtRaghkumarTentu** [lessmore92/PHPEthereumERC20#11]
hello Sir , While Running This Code Im Getting Below Error. Can You Help Me With This.

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201
Stack trace:
#0 C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 C:\Users\hp\OneDrive\Desktop\tes in C:\Users\hp\OneDrive\Desktop\testLibrarySdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201
PS C:\Users\hp\OneDrive\Desktop\testLibrarySdk\src\test>

**Comment by lessmore92** [comment]
Hi, please show your code

**Comment by lhtRaghkumarTentu** [comment]
`<?php

require_once "vendor/autoload.php";


class USDT extends \Lessmore92\Ethereum\Foundation\StandardERC20Token 
{
    protected $contractAddress = "0xdac17f958d2ee523a2206206994597c13d831ec7";  
}

$tether = new USDT("https://mainnet.infura.io/v3/API_KEY");

var_dump($tether->name());
var_dump($tether->decimals());


?>`

**Comment by lhtRaghkumarTentu** [comment]
when I Run This Code I Found Below Error.

PS C:\Users\hp\OneDrive\Desktop\teswt1> php index.php
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\hp\OneDrivStack trace:
#0 C:\Users\hp\OneDrive\Desktop\teswt1\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#3 C:\Users\hp\OneDrive\Desktop\teswt1\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 C:\Users\hp\OneDrive\Desktop\teswt1\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 C:\Users\hp\OneD in C:\Users\hp\OneDrive\Desktop\teswt1\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201

**Comment by lessmore92** [comment]
Look at this https://stackoverflow.com/a/34883260/1804223 I think this solves your issue.

**Comment by lessmore92** [comment]
Did your problem solve?

**Comment by lessmore92** [comment]
closed due to inactivity
