### ISSUE TITLE
mb_substr(): Argument #2 ($start) must be of type int, float given

### ISSUE THREAD

**Issue by 99hops** [lessmore92/PHPEthereumERC20#14]
```
$tokeData = new Token('0xb01d449c7a740c1f29a39b46aebf4b16f9877981', $node);
$tokeData->name()
```

`mb_substr(): Argument #2 ($start) must be of type int, float given`

Looks like there is an issue with name of [this token](https://bscscan.com/token/0xb01d449c7a740c1f29a39b46aebf4b16f9877981)

**Comment by nathanielajayi7** [comment]
What even is that !!!?

**Comment by 99hops** [comment]
```file = "php-erc20/src/Token.php"
line = {int} 26
function = "call"
class = "Lessmore92\Ethereum\Foundation\ERC20"
type = "->"
args = {array} ['name']
...
call_user_func_array([$this->contract->at($this->contractAddress), 'call'], $params); line 81

web3.php/src/Contracts/SolidityType.php line 263
```

I don't know what event you are talking about, it's just a call to get the name, but it's looks it's not a problem with this lib.
So there aren't many options here except to handle the error if that's an option.

**Comment by nathanielajayi7** [comment]
> ```
> line = {int} 26
> function = "call"
> class = "Lessmore92\Ethereum\Foundation\ERC20"
> type = "->"
> args = {array} ['name']
> ...
> call_user_func_array([$this->contract->at($this->contractAddress), 'call'], $params); line 81
> 
> web3.php/src/Contracts/SolidityType.php line 263
> ```
> 
> I don't know what event you are talking about, it's just a call to get the name, but it's looks it's not a problem with this lib. So there aren't many options here except to handle the error if that's an option.

I was referring to the name of the Token because it seems the character are not using standard encoding for text? Anyway, you can try 

`try {
//get name
}catch(Throwable $e){
//Fallback 
}`

The problem is not with the library

**Comment by 99hops** [comment]
I agree, just wanted to share it :wink:

**Comment by 27078566** [comment]
The account balance is enough to initiate USDT transfer, but prompt  insufficient funds for gas * price + value

**Comment by 27078566** [comment]
Ask for help on how to set parameters. Use the default gaslimits (50000) and real-time gas (76044395808) to prompt me TX fee (XX ether) exceeds the configured cap (1.00 ether)
