### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by ydlds** [lessmore92/PHPEthereumERC20#15]
insufficient funds for gas * price + value

owner_address 12 usdt 
myapp_address  is 0.08eth

**Comment by lessmore92** [comment]
Usually, `gasPrice` and `gasLimit` caused this error.
Please check those values.

**Comment by ydlds** [comment]
Adjust the gasprice to very low, it is normal, but the transaction is very slow, can you fix it? Thank you so much

**Comment by ydlds** [comment]
我是一个中国人，不会英文

**Comment by lessmore92** [comment]
> Adjust the gasprice to very low, it is normal, but the transaction is very slow, can you fix it? Thank you so much

No, You can adjust those values based on your usage

**Comment by ydlds** [comment]
The sent gasprice is not a normal value, and the wei value re-obtained on the main network also prompts an insufficient error. There is no problem with using web3.js, but there should be a problem with the package processing the gasprice value.
